### PR TITLE
Enable to define the required feature flag for an API

### PR DESCRIPTION
**Pull request by jskelin**
#### What this PR does / Why we need it:
There is a need to hide specific classic endpoints under development. For that reason api.API structure is expanded with a new field, and new filtering is added to prepareAPIs function

### CODE REVIEW

**Comment by warber** [comment]
lgtm, Only one concern with a general FF name lice "MONACO_EXPERIMENTAL" from my side is that if this gets used more often, it becomes unclear/hard see what **exactly** this FF is affecting. Imo we can be more specific like "MONACO_FEAT_KUA_API".

**Comment by jskelin** [comment]
> lgtm, Only one concern with a general FF name lice "MONACO_EXPERIMENTAL" from my side is that if this gets used more often, it becomes unclear/hard see what **exactly** this FF is affecting. Imo we can be more specific like "MONACO_FEAT_KUA_API".

Regarding the actual Feature flag, `MONACO_EXPERIMENTAL` should be a general flag for a new feature so that `main` is always deployable. Because it is not yet defined what the scope of the new feature, it is questionable whether it should be just `key-user-actions-*` (e.g. `MONACO_FEAT_KUA_API`), or the whole `(M)RUM support` (e.g. `MONACO_FEAT_(M)RUM`)?

Either way, I don't have strong opinion on the name of the FF.

**Review by warber — APPROVED** [review]

**Review by warber — CHANGES_REQUESTED** [review]
e2e tests

**Comment by jskelin** [comment]
> e2e tests

e2e tests passes now

**Review by warber — APPROVED** [review]

**Pull request merged**
